### ISSUE TITLE
Bug ustl::remove_copy_if

### ISSUE THREAD

**Issue by fhirmann** [IAIK/sweb#125]
I found a bug in the implementation of ustl::remove_copy_if.  This also affects the ustl::remove_if which is often used for erasing elements in containers.

The implementation should be:
_Remove_copy_if copies elements from the range [first, last) to a range beginning at result, except that elements for which pred is true are not copied._

There is a missing negation at `pred (*first)` so the function should be:

```c++
inline OutputIterator remove_copy_if (InputIterator first, InputIterator last, OutputIterator result, Predicate pred)
{
  for (; first != last; ++first)
    if (!pred (*first))
      *result++ = *first;
  return result;
}
```

**Comment by dgruss** [comment]
That's right.

This issue is already fixed in the upstream ustl: 
https://github.com/msharov/ustl/issues/66

I will update the ustl integrated in SWEB sooner or later to pull 
these bugfixes in.

**Comment by fhirmann** [comment]
Thanks for your fast response.
