### ISSUE TITLE
Do the addresses of functions in boot.32.C need to truncate?

### ISSUE THREAD

**Issue by stormycatcat** [IAIK/sweb#143]
x86/64/source/boot.32.C
The kernel is loaded in 0x10000, and it's virtual address starts from 0xFFFFFFFF80100000. I know the addr of data has been transfered to physical addr in this file, but the functions defined within the file such as print, are called directly without being transfered to physical addr. I want to know why the virtual addr can be called directly. 
Thank you.

**Comment by dgruss** [comment]
On 23.01.2018 08:08, stormycatcat wrote:
> x86/64/source/boot.32.C
> The kernel is loaded in 0x10000, and it's virtual address starts from 0xFFFFFFFF80100000. I know the addr of data has
> been transfered to physical addr in this file, but the functions defined within the file such as print, are called
> directly without being transfered to physical addr. I want to know why the virtual addr can be called directly.

The compiler usually (and in all situations that we find in this file) avoids generating code with jumps to absolute
64bit addresses, instead it uses relative jumps. Consequently, you have no problem with the function calls in here.


Cheers,
Daniel

**Comment by dgruss** [comment]
So yes, you need to truncate.
