### ISSUE TITLE
arm_verdex and arm_rpi2 not booting

### ISSUE THREAD

**Issue by Woazboat** [IAIK/sweb#169]
arm_verdex crashes on boot:
```Removing Boot Time Ident Mapping...
[PM         ]Ctor: memory region from physical 0x0 to 0x0x76a000 of type 1
[PM         ]Ctor: usable memory region: start_page: 0, end_page: 1898, type: 1
[PM         ]Ctor: Marking stuff mapped in above 2 and < 3 gig as used
[PM         ]Ctor: Marking GRUB loaded modules as reserved
[PM         ]Ctor: module: start_page: 0, end_page: 267
KERNEL PANIC: Assertion bit_number < size_ failed in File sweb/common/source/util/Bitmap.cpp on Line 37
```

arm_rpi2 does not produce any console output and just shows a black screen

**Comment by dgruss** [comment]
On 01.06.2018 01:45, Woazboat wrote:
> arm_verdex crashes on boot:
> ```Removing Boot Time Ident Mapping...
> [PM         ]Ctor: memory region from physical 0x0 to 0x0x76a000 of type 1
> [PM         ]Ctor: usable memory region: start_page: 0, end_page: 1898, type: 1
> [PM         ]Ctor: Marking stuff mapped in above 2 and < 3 gig as used
> [PM         ]Ctor: Marking GRUB loaded modules as reserved
> [PM         ]Ctor: module: start_page: 0, end_page: 267
> KERNEL PANIC: Assertion bit_number < size_ failed in File sweb/common/source/util/Bitmap.cpp on Line 37
> ```
> 
> arm_rpi2 does not produce any console output and just shows a black screen

Ok, probably a bisect would reveal where that comes from...

**Comment by misc0110** [comment]
arm_rpi2 works again with 7855b6193895604bb294acc34de3ab1eab57a034
