### ISSUE TITLE
arm_rpi uses deprecated qemu-system-arm-rpi

### ISSUE THREAD

**Issue by Woazboat** [IAIK/sweb#170]
The custom [qemu-system-arm-rpi](https://github.com/Torlus/qemu.git) build used for arm_rpi no longer exists because it has been upstreamed to https://github.com/qemu/qemu

**Comment by dgruss** [comment]
On 01.06.2018 01:50, Woazboat wrote:
> The custom [qemu-system-arm-rpi](https://github.com/Torlus/qemu.git) build used for arm_rpi no longer exists because it has been upstreamed to https://github.com/qemu/qemu
> 

That's right, but we don't use that anymore anyway. Are there still
references to it?

**Comment by dgruss** [comment]
i think that's all outdated

**Comment by dgruss** [comment]
i think @misc0110 is removing arm_rpi support and fixing arm_rpi2 while doing that...
