### ISSUE TITLE
-mgeneral-regs-only on x86?

### ISSUE THREAD

**Issue by dgruss** [IAIK/sweb#181]
Should we use -mgeneral-regs-only somewhere just to be sure?

**Comment by Ferdi265** [comment]
especially if students enable optimizations at some point, it can happen that some of the instruction set extension flags (`-msse` and friends) are not set, and gcc will try to use that to vectorize code.

if that happens in userspace, fun things happen at/around context switches.

so yes, `-mgeneral-regs-only` seems reasonable as long as SWEB has no support for saving/restoring floating point state.

**Comment by dgruss** [comment]
We do support FPU in userspace, so at least older SSE versions should
work...

**Comment by Woazboat** [comment]
Relevant issue: #223

**Comment by dgruss** [comment]
already implemented
