### ISSUE TITLE
ustl upstream is officially obsolete

### ISSUE THREAD

**Issue by Woazboat** [IAIK/sweb#198]
https://github.com/msharov/ustl/commit/1fc8eb7290de31dded74076fdceea72dec83ab71

**Comment by dgruss** [comment]
Yeah, we can't use the official C++ library so we'll likely stick with
the most recent version...

**Comment by Woazboat** [comment]
https://github.com/electronicarts/EASTL is potentially an alternative, although I haven't looked into it very much

**Comment by dgruss** [comment]
In sweb we don't have the problems other projects might have from using
obsolete libraries, so I would not switch the library unless we run into
problems with ustl or we gain something else by switching. For now it
looks fine to not invest time into switching the library.

**Comment by Woazboat** [comment]
Agreed. It's not a big issue now, although it might be in the future.
