### ISSUE TITLE
ARM Verdex: Kernel too large

### ISSUE THREAD

**Issue by misc0110** [IAIK/sweb#253]
The ARM Verdex version fails in the CI, as the kernel image is too large. QEMU expects a 32MB flash, and the kernel is copied to offset 31MB of the flash: https://github.com/IAIK/sweb/blob/a86c7e5b679aaf766f2163ba14975ca89559bc15/arch/arm/verdex/utils/makeflash.sh#L9
With the current kernel size of >1.5MB, this fails, and SWEB does not boot.

**Comment by dgruss** [comment]
maybe we scrap verdex?

**Comment by misc0110** [comment]
I'm not sure if anyone uses that anyway, so this could be a solution

**Comment by misc0110** [comment]
Alternatively, we disable the debug infos for verdex, then it should fit again.

**Comment by Woazboat** [comment]
Also relevant here: https://github.com/IAIK/sweb/pull/247

(I previously added a check for that issue in that PR)

**Comment by misc0110** [comment]
Why was that PR reverted?

**Comment by dgruss** [comment]
Introducing unnecessary dependencies and complexity.Am 12.05.2021 19:11 schrieb Michael Schwarz ***@***.***>:
Why was that PR reverted?

**Comment by misc0110** [comment]
As far as i can see, it doesn't solve the issue and just aborts when the kernel is too large. I see three options:
1. Disable debug information for Verdex (remove `-gstabs2` in https://github.com/IAIK/sweb/blob/a86c7e5b679aaf766f2163ba14975ca89559bc15/arch/arm/verdex/CMakeLists.include#L3) - this gets the kernel to ~400kb, it boots again, but it runs into an assert regarding memory corruption -> someone would have to debug that
2. Remove Verdex from the CI pipeline (ugly)
3. Remove Verdex entirely

**Comment by dgruss** [comment]
Option 3 is best.

**Comment by misc0110** [comment]
Removed in dc523bab2bee91a3e3788381f6f8b96813ef4abc
