### ISSUE TITLE
64bit backtraces are missing

### ISSUE THREAD

**Issue by dgruss** [IAIK/sweb#49]
Backtraces should at least print the return addresses!

To print pretty backtraces i see different options:
1. parse dwarf-2
2. pass the information somehow else... (which might be easier)

**Comment by dgruss** [comment]
i think this issue is not up2date anymore, don't we have 64bit backtraces now?

**Comment by fkirc** [comment]
I debugged for 64 bit yesterday, there are still no backtraces

**Comment by dgruss** [comment]
should be in https://github.com/IAIK/sweb/commits/devel but that code is not tested much....

**Comment by fkirc** [comment]
I think that when this backtrace code is working well, and when 64 bit archmemory gets a detailed review looking for possible remaining bugs, then it might be doable to shift to 64 bit default next semester

**Comment by misc0110** [comment]
They are now implemented (4d518f67212fc9c129356130b09225be9125bf73)
