### ISSUE TITLE
missing LICENSE

### ISSUE THREAD

**Issue by stefan2904** [IAIK/sweb#52]
what's the license of sweb?

consider adding a LICENSE file.
https://help.github.com/articles/open-source-licensing/

**Comment by PeterTheOne** [comment]
+1

**Comment by GhostLyrics** [comment]
I am very interested in seeing a license added to the project.

Last time I talked about this to @dgruss the argument was that SWEB is Open Source, but not Free Open Source, meaning, you can read what is done, you can see how things work, but you may not build upon that code. The preliminary answer I got back then was **Won't fix**.

As far as I understood his point, the idea behind that is to prohibit as many use cases outside of the *Operating Systems* course at TU Graz as possible, even going as far as being able to sue existing (public) mirrors of said code out of existence if necessary. - The reasoning behind this is to prevent students who have successfully finished the course from sharing solutions to the tasks required in the course which usually change little from year to year.

Personally though, I'd like to know what may be done with the contributions I have sent (and intend to keep on sending) upstream in terms of licensing.

**Comment by GhostLyrics** [comment]
As an aside, this has also shortly been discussed in #8.

**Comment by dgruss** [comment]
@stefan2904 https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license "This might not be what you intend." - it is exactly what we intend. We don't mind forking (which is not equivalent to creating derivative work).

Therefore, the answer is again: Won't fix, as @GhostLyrics already explained.

@GhostLyrics: you are the copyright owner of your contributions. by committing something into this repository it is published as a part of the project and the project as a whole is under copyrighted.
In EU there is no such thing as copyright transfer, so you keep your rights and can send the same patches somewhere else as well. however, you are not allowed to publish derived work (clearly more than a few patches).
Finally: very short code passages might not be covered by copyright law at all, but you would have to ask someone else on that topic.

**Comment by stefan2904** [comment]
@dgruss "Generally speaking, the absence of a license means that the default copyright laws apply" - implicit rules are always worse than explicit rules. I like the way ITSec did it (I don't like their license, but I like that they make clear what the terms are).

> We don't mind forking (which is not equivalent to creating derivative work).

Which is already not clear to me what you mean. What's the difference between "forking" and "creating derivative work"?

**Comment by dgruss** [comment]
Am 06.06.2015 um 18:55 schrieb Stefan:
> implicit rules are always worse than explicit rules.

that's certainly not true when it comes to law related stuff...

one should never try to write licenses etc. without professional
legal education and experience.

however, the rules are explicit. look up "urheberrecht" somewhere..
not so few explicit rules ;)

> Which is already not clear to me what you mean. What's the difference between "forking" and "creating derivative work"?

derivative work are non-trivial changes (more than a few bugfixes,
debug statements, etc.)

by merely forking a repository you do not change anything -> not
creating derivative work
however, you then may not create derivative work in your own fork of
the repository (covered by copyright)
