### ISSUE TITLE
userstacktraces not working on arm_icp anymore

### ISSUE THREAD

**Issue by dgruss** [IAIK/sweb#57]

**Comment by dgruss** [comment]
does the new debug format have any influence on the ARM variants?

**Comment by misc0110** [comment]
keyboard is not working on arm_icp anymore, when did that break?

**Comment by dgruss** [comment]
was not aware of that...

**Comment by misc0110** [comment]
how did you test the usertrace?

**Comment by dgruss** [comment]
just f11/f12...
