### ISSUE TITLE
strncmp bug?

### ISSUE THREAD

**Issue by dgruss** [IAIK/sweb#74]
strncmp is broken i think...
compare a 5 letter string to a second longer string with strncmp(str1,str2,5) returns non-zero although it should
compare the same string with memcmp(str1,str2,5) returns zero as it should

**Comment by dgruss** [comment]
https://github.com/IAIK/sweb/blame/master/common/source/util/kstring.cpp#L306

**Comment by dkales** [comment]
return (*(uint8 *) str1 - *(uint8 *) str2);
doesnt work for your case, since it would return '\0' minus the char in the second string, although it should return 0;

maybe something like return n == 0 ? 0 : (*(uint8 *) str1 - *(uint8 *) str2);

**Comment by dkales** [comment]
other maybe "nicer" variant would be 

extern "C" int32 strncmp(const char *str1, const char *str2, size_t n)
{
  while (n-- && (*str1) && (*str2))
  {
    if (*str1 != *str2)
    {
      return (*(uint8 *) str1 - *(uint8 *) str2);
    }
    ++str1;
    ++str2;
  }
  return 0;
}

**Comment by dgruss** [comment]
yes, sounds good.

**Comment by dkales** [comment]
ok second variant doesnt work, fails when one string is shorter than n, first one should be fine though

**Comment by dgruss** [comment]
do you want to commit it?
