### ISSUE TITLE
cmake custom targets "install" und "help" verstoßen gegen cmake 3.0 policies

### ISSUE THREAD

**Issue by MarkusTeufelberger** [IAIK/sweb#9]
Siehe http://www.cmake.org/cmake/help/v3.0/policy/CMP0037.html

Zeilen 241 und 375 in https://github.com/IAIK/sweb/blob/master/CMakeLists.txt produzieren Warnings mit cmake 3.0.2, da "install" und "help" schon reservierte Target names sind.

**Comment by GhostLyrics** [comment]
Can we reopen this? Current code explicitly silences the warnings without correcting the actual problem. Telling the checker to 'move along, nothing here to see' is really bad style.

**Comment by MarkusTeufelberger** [comment]
Has to be reopened by Daniel, or you just submit a patch/pull request to fix the issue.

**Comment by dgruss** [comment]
code does not silence warnings but specify cmake behaviour. it's a cmake feature.

**Comment by MarkusTeufelberger** [comment]
I read a bit more into cmake and while a few things in the CMakeLists.txt files could (should?) be rewritten e.g. for portability (a lot of standard UNIX tools are hardcoded that can be managed by cmake instead like deleting folders or copying/moving files), the current custom "help" target however is much better than the one generated by default (which just lists all possible targets with 0 explanation and provides no way to add an explanation either as far as I've googled). The custom "install" target might be helpful since the default behaviour might not be what people using sweb actually want. It could be probably renamed to something else though (create_hdd_image or something like that).

All in all, the make targets are probably a bit too powerful compared to what they are typically used for, the alternative though would be to supply a few standard shell scripts which is also not ideal and in the current situation from the user's perspective you at least only have to interact with make instead of dealing with lots of confused people that have to learn how to set the executable bit on a shell script or to remember to type ./ before running something...

**Comment by dgruss** [comment]
yes, i agree.
i remember the help target as the point where i decided that this policy does not make sense in our case.
so, i would not change anything here, and therefore no reopen is necessary ;)
